spring:
  profiles: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest
  zipkin:
    enabled: false
server:
  port: 8761

eureka:
  instance:
    hostname: registry
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://config:8761/eureka/
    #   registerWithEureka是否向注册中心注册自己
    registerWithEureka: false
    #   fetchRegistry是否需要去检索服务
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
  server:
    ## 主动失效检测间隔,配置成5秒
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
    ## 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    renewal-threshold-update-interval-ms: 120000
    use-read-only-response-cache: false
